package com.hollandjake.dogbot.util;

public enum BrowserStatus {
    INIT_DRIVER,
    INIT_DRIVER_COMPLETE,
    INIT_BROWSER,
    INIT_BROWSER_COMPLETE,
    LOGGING_IN,
    LOGGING_IN_COMPLETE,
    GATHERING_DETAILS,
    GATHERING_DETAILS_COMPLETE,
    AWAITING_MESSAGE,
    PROCESSING_MESSAGE,
    SENDING_MESSAGE,
    LOADING,
    CLOSED
}
